# Generated by Django 2.2.7 on 2019-11-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
